//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_FluxoCaixa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fluxodecaixa
    {
        public int fluxodecaixaid { get; set; }
        public System.DateTime data { get; set; }
        public double qtd { get; set; }
        public decimal valorproduto { get; set; }
        public string tipodemovimento { get; set; }
        public Nullable<int> despesaId { get; set; }
        public Nullable<int> fornecedorId { get; set; }
        public Nullable<int> produtoId { get; set; }
        public Nullable<int> clienteId { get; set; }
        public int tipodelancamentoId { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual despesa despesa { get; set; }
        public virtual fornecedor fornecedor { get; set; }
        public virtual produto produto { get; set; }
        public virtual tipodelancamento tipodelancamento { get; set; }
    }
}
